"""Generate a hardened Dockerfile (+ .dockerignore) when the repo has none, and lint any Dockerfile."""
from __future__ import annotations

import re
from pathlib import Path

DOCKERIGNORE = """.git
.gitignore
**/__pycache__
**/*.pyc
.venv
venv
env
.env
.env.*
*.env
.secrets
tests
.pytest_cache
.coverage
.coveragerc
htmlcov
.cip*
.idea
.vscode
node_modules
*.log
Dockerfile*
"""


def detect_start_command(evidence: dict) -> tuple[list[str], int]:
    """Figure out how to start the app from AST evidence."""
    ast_info = evidence["ast"]
    deps = {d["name"] for d in evidence["dependencies"]["dependencies"]}
    streamlit = [a for a in ast_info["app_objects"] if a["type"] == "Streamlit"]
    if streamlit:
        return ["streamlit", "run", streamlit[0]["file"], "--server.port=8501", "--server.address=0.0.0.0",
                "--server.headless=true"], 8501
    apps = [a for a in ast_info["app_objects"] if a["type"] in ("FastAPI", "Flask")]
    if apps:
        a = apps[0]
        module = a["file"].removesuffix(".py").replace("/", ".")
        if a["type"] == "FastAPI":
            return ["uvicorn", f"{module}:{a['name']}", "--host", "0.0.0.0", "--port", "8000"], 8000
        if "gunicorn" in deps:
            return ["gunicorn", "-b", "0.0.0.0:8000", f"{module}:{a['name']}"], 8000
        return ["python", "-m", "flask", "--app", f"{module}:{a['name']}", "run", "--host", "0.0.0.0", "--port", "8000"], 8000
    entries = ast_info.get("entry_points") or []
    main = next((e for e in entries if Path(e).name in ("main.py", "app.py", "run.py", "__main__.py")), entries[0] if entries else "main.py")
    return ["python", main], 0


def health_path(evidence: dict) -> str | None:
    """URL the smoke run calls to prove the app answers HTTP (None = only check it stays up)."""
    kinds = {a["type"] for a in evidence["ast"]["app_objects"]}
    if "Streamlit" in kinds:
        return "/_stcore/health"
    if "FastAPI" in kinds:
        return "/docs"
    if "Flask" in kinds:
        return "/"
    return None


def generate_dockerfile(workspace: Path, evidence: dict, base_image: str) -> dict:
    cmd, port = detect_start_command(evidence)
    has_reqs = (workspace / "requirements.txt").exists()
    has_pyproject = (workspace / "pyproject.toml").exists()
    if "uvicorn" in cmd[0] and not any(d["name"] == "uvicorn" for d in evidence["dependencies"]["dependencies"]):
        extra_install = "RUN pip install --no-cache-dir uvicorn\n"
    else:
        extra_install = ""
    install = ("COPY requirements.txt .\nRUN pip install --no-cache-dir -r requirements.txt\n" if has_reqs else
               "COPY pyproject.toml ./\nCOPY . .\nRUN pip install --no-cache-dir .\n" if has_pyproject else "")
    cmd_json = "[" + ", ".join(f'"{c}"' for c in cmd) + "]"
    healthcheck = (f'HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 \\\n'
                   f'  CMD python -c "import socket; socket.create_connection((\'127.0.0.1\', {port}), timeout=4)" || exit 1\n'
                   if port else "")
    dockerfile = f"""# Generated by Code Intelligence Platform (CIP)
FROM {base_image}

ENV PYTHONDONTWRITEBYTECODE=1 \\
    PYTHONUNBUFFERED=1 \\
    PIP_DISABLE_PIP_VERSION_CHECK=1

WORKDIR /app

# Dependencies first for better layer caching
{install}{extra_install}
# Application code (.dockerignore keeps .env, tests, VCS data out of the image)
COPY . .

# Run as an unprivileged user
RUN useradd --create-home --uid 10001 appuser && chown -R appuser:appuser /app
USER appuser

{"EXPOSE " + str(port) if port else ""}
{healthcheck}
CMD {cmd_json}
"""
    dockerfile = re.sub(r"\n{3,}", "\n\n", dockerfile)
    (workspace / "Dockerfile").write_text(dockerfile, encoding="utf-8")
    if not (workspace / ".dockerignore").exists():
        (workspace / ".dockerignore").write_text(DOCKERIGNORE, encoding="utf-8")
    return {"generated": True, "start_command": cmd, "port": port}


def ensure_dockerignore(workspace: Path) -> bool:
    if (workspace / ".dockerignore").exists():
        return False
    (workspace / ".dockerignore").write_text(DOCKERIGNORE, encoding="utf-8")
    return True


def lint_dockerfile(dockerfile: Path, workspace: Path) -> dict:
    """Lightweight Dockerfile checks answering the questions from the design (root user, secrets, pinning ...)."""
    text = dockerfile.read_text(encoding="utf-8", errors="replace")
    lines = text.splitlines()
    issues = []

    def add(sev, rule, msg, line=0):
        issues.append({"severity": sev, "rule": rule, "message": msg, "line": line})

    froms = [(i + 1, l) for i, l in enumerate(lines) if l.strip().upper().startswith("FROM ")]
    for ln, l in froms:
        image = l.split()[1]
        if ":" not in image.split("/")[-1] or image.endswith(":latest"):
            add("MEDIUM", "DF001", f"Base image '{image}' not pinned to a specific tag", ln)
        if not any(s in image for s in ("slim", "alpine", "distroless", "chainguard")):
            add("LOW", "DF002", f"Base image '{image}' is not a slim/minimal variant (larger attack surface)", ln)
    users = [l for l in lines if l.strip().upper().startswith("USER ")]
    if not users or users[-1].split()[1] in ("root", "0"):
        add("HIGH", "DF003", "Container runs as root – add a non-root USER")
    for i, l in enumerate(lines, 1):
        s = l.strip()
        up = s.upper()
        if up.startswith("ADD ") and not re.search(r"\.(tar|gz|tgz|xz)\b", s):
            add("LOW", "DF004", "Use COPY instead of ADD for local files", i)
        if re.search(r"(COPY|ADD)\s+.*\.env\b", s):
            add("HIGH", "DF005", ".env file copied into the image", i)
        if re.search(r"(ENV|ARG)\s+\w*(SECRET|PASSWORD|TOKEN|API_KEY|APIKEY)\w*\s*=?\s*\S+", s, re.I):
            add("HIGH", "DF006", "Secret-like value baked into ENV/ARG", i)
        if "pip install" in s and "--no-cache-dir" not in s:
            add("LOW", "DF007", "pip install without --no-cache-dir increases image size", i)
        if re.search(r"apt-get install(?!.*--no-install-recommends)", s):
            add("LOW", "DF008", "apt-get install without --no-install-recommends", i)
        if ("curl" in s or "wget" in s) and ("| sh" in s or "| bash" in s):
            add("MEDIUM", "DF009", "Piping remote script into shell", i)
    if not any(l.strip().upper().startswith("HEALTHCHECK") for l in lines):
        add("LOW", "DF010", "No HEALTHCHECK defined")
    copies_all = any(re.match(r"COPY\s+\.\s+", l.strip(), re.I) for l in lines)
    dockerignore = workspace / ".dockerignore"
    if copies_all:
        ignored = dockerignore.read_text(encoding="utf-8") if dockerignore.exists() else ""
        if ".env" not in ignored and any(workspace.glob(".env*")):
            add("HIGH", "DF011", "'COPY . .' with a .env file present and not excluded by .dockerignore")
        if not dockerignore.exists():
            add("MEDIUM", "DF012", "'COPY . .' without a .dockerignore – VCS data, caches and secrets may leak into the image")
    reqs = workspace / "requirements.txt"
    if reqs.exists():
        unpinned = [l for l in reqs.read_text(encoding="utf-8").splitlines()
                    if l.strip() and not l.startswith(("#", "-")) and "==" not in l]
        if unpinned:
            add("MEDIUM", "DF013", f"{len(unpinned)} requirements not pinned with == (non-reproducible builds)")
    expose = [l for l in lines if l.strip().upper().startswith("EXPOSE ")]
    counts = {s: sum(1 for x in issues if x["severity"] == s) for s in ("HIGH", "MEDIUM", "LOW")}
    return {"issues": issues, "high": counts["HIGH"], "medium": counts["MEDIUM"], "low": counts["LOW"],
            "exposed_ports": [p for l in expose for p in l.split()[1:]]}
