"""Generate, validate, repair and (if still failing) prune/quarantine pytest tests.

Generated tests are never trusted blindly: every file is executed; failing tests are sent back
to the LLM for repair, and whatever still fails is removed and reported.
"""
from __future__ import annotations

import ast
import json
import logging
import re
import shutil
from pathlib import Path

from cip.llm.client import LLMClient, extract_code, load_prompt
from cip.llm.context_builder import build_module_context
from cip.testing.test_runner import TestEnvironment, run_pytest

log = logging.getLogger("cip.testgen")
GEN_DIR = Path("tests") / "cip_generated"


def dummy_env(env_vars: list[str]) -> dict:
    env = {}
    for name in env_vars:
        u = name.upper()
        if "MONGO" in u and ("URI" in u or "URL" in u):
            env[name] = "mongodb://localhost:27017"
        elif "PORT" in u:
            env[name] = "8080"
        elif "URL" in u or "URI" in u or "ENDPOINT" in u or "HOST" in u:
            env[name] = "http://localhost"
        elif u.startswith(("DEBUG", "ENABLE", "USE_")):
            env[name] = "false"
        else:
            env[name] = "cip-test-value"
    return env


# ------------------------------------------------------------------ offline smoke tests
def smoke_tests(module: dict) -> str:
    mod = module["module"]
    info = module["info"]
    if module.get("kind") == "streamlit":
        return (
            '"""Smoke tests generated by CIP (offline mode) for a Streamlit app, using Streamlit\'s own AppTest."""\n'
            "from pathlib import Path\n\n"
            "from streamlit.testing.v1 import AppTest\n\n"
            f'APP = Path(__file__).resolve().parents[2] / "{module["file"]}"\n\n\n'
            "def test_app_renders_without_exceptions():\n"
            "    at = AppTest.from_file(str(APP), default_timeout=60)\n"
            "    at.run()\n"
            "    assert not at.exception, [e.value for e in at.exception]\n\n\n"
            "def test_app_shows_a_title():\n"
            "    at = AppTest.from_file(str(APP), default_timeout=60)\n"
            "    at.run()\n"
            "    assert len(at.title) >= 1\n"
        )
    if module.get("kind") == "script":
        return (
            '"""Smoke test generated by CIP (offline mode) for a script-style module: it must at least compile."""\n'
            "import py_compile\nfrom pathlib import Path\n\n"
            f'SCRIPT = Path(__file__).resolve().parents[2] / "{module["file"]}"\n\n\n'
            "def test_script_compiles():\n"
            "    py_compile.compile(str(SCRIPT), doraise=True)\n"
        )
    lines = ['"""Smoke tests generated by CIP (offline mode – no LLM configured)."""',
             "import importlib", "", "import pytest", "", f'MODULE = "{mod}"', "", "",
             "def test_module_imports():", "    importlib.import_module(MODULE)", ""]
    apps = {a["name"]: a["type"] for a in info["app_objects"]}
    for r in info["routes"]:
        if "{" in r["path"] or "<" in r["path"] or r["method"] != "GET" or r["object"] not in apps:
            continue
        kind = apps[r["object"]]
        safe = re.sub(r"\W+", "_", r["path"]).strip("_") or "root"
        if kind in ("FastAPI", "APIRouter"):
            lines += ["", f"def test_get_{safe}_does_not_500():",
                      "    from fastapi import FastAPI",
                      "    from fastapi.testclient import TestClient",
                      f"    obj = getattr(importlib.import_module(MODULE), \"{r['object']}\")",
                      "    app = obj if isinstance(obj, FastAPI) else FastAPI()",
                      "    if app is not obj:",
                      "        app.include_router(obj)",
                      "    with TestClient(app, raise_server_exceptions=False) as client:",
                      f"        assert client.get(\"{r['path']}\").status_code < 500", ""]
        elif kind == "Flask":
            lines += ["", f"def test_get_{safe}_does_not_500():",
                      f"    app = getattr(importlib.import_module(MODULE), \"{r['object']}\")",
                      f"    assert app.test_client().get(\"{r['path']}\").status_code < 500", ""]
    return "\n".join(lines) + "\n"


# ------------------------------------------------------------------ pruning
def _failing_names(failures: list[dict]) -> set[str]:
    names = set()
    for f in failures:
        name = f["test"].split("::")[-1]
        names.add(name.split("[")[0])
    return names


def prune_failing(path: Path, failures: list[dict]) -> int:
    """Remove failing test functions from a test file. Returns number removed (-1 if unparsable)."""
    names = _failing_names(failures)
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"))
    except SyntaxError:
        return -1
    removed = 0

    def keep(node) -> bool:
        nonlocal removed
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name in names:
            removed += 1
            return False
        return True

    tree.body = [n for n in tree.body if keep(n)]
    for n in tree.body:
        if isinstance(n, ast.ClassDef):
            n.body = [m for m in n.body if keep(m)] or [ast.Pass()]
    path.write_text(ast.unparse(tree) + "\n", encoding="utf-8")
    return removed


# ------------------------------------------------------------------ main entry
CONFTEST = '''"""Written by CIP: isolates generated tests so a fake/stub module created by one test can never
leak into another test and hide a real import error."""
import sys

import pytest


@pytest.fixture(autouse=True)
def _cip_isolate_imports():
    before = dict(sys.modules)
    yield
    for name in list(sys.modules):
        if name not in before:
            del sys.modules[name]
    sys.modules.update(before)
'''

_STUB = re.compile(r"sys\.modules\[\s*[\"\']([\w.]+)[\"\']\s*\]\s*=|setitem\(\s*sys\.modules\s*,\s*[\"\']([\w.]+)")


def stubbed_imports(code: str, module_imports: list[str]) -> list[str]:
    """Modules the test REPLACES with fakes although the app really imports them (would hide import errors)."""
    app_roots = {i.lstrip(".").split(".")[0] for i in module_imports}
    names = {a or b for a, b in _STUB.findall(code)}
    return sorted(n for n in names if n.split(".")[0] in app_roots)


def _run(tenv, fname, out_dir, env):
    return run_pytest(tenv, [str(GEN_DIR / fname)], out_dir / "runs", fname[:-3], extra_env=env)


def generate_tests(workspace: Path, modules: list[dict], tenv: TestEnvironment, llm: LLMClient,
                   app_summary: dict, out_dir: Path, env_vars: list[str], max_repairs: int = 2) -> dict:
    """Per module: (1) a deterministic smoke test, always kept – if it fails the app itself is broken;
    (2) with an LLM, a full test file that is run, repaired, and pruned/quarantined if it still fails."""
    gen_dir = workspace / GEN_DIR
    gen_dir.mkdir(parents=True, exist_ok=True)
    (gen_dir / "conftest.py").write_text(CONFTEST, encoding="utf-8")
    quarantine = out_dir / "quarantine"
    env = dummy_env(env_vars)
    report = {"mode": "llm + smoke" if llm.enabled else "smoke (offline)", "files": [], "quarantined": [],
              "suspected_defects": [], "removed_tests": [], "runtime_failures": [], "stubbed_imports": []}

    for m in modules:
        slug = re.sub(r"\W+", "_", m["module"])

        # (1) smoke test – too simple to be wrong, never pruned: a failure = the app is broken
        fname = f"test_cip_smoke_{slug}.py"
        (gen_dir / fname).write_text(smoke_tests(m), encoding="utf-8")
        result = _run(tenv, fname, out_dir, env)
        entry = {"module": m["module"], "file": (GEN_DIR / fname).as_posix(), "mode": "smoke", "attempts": 0,
                 "passed": result["passed"], "failed": result["failed"] + result["errors"]}
        entry["status"] = "failing" if entry["failed"] else "ok"
        for f in result["failures"]:
            report["runtime_failures"].append({"module": m["module"], "test": f["test"], "error": f["message"][:400]})
        report["files"].append(entry)

        if not llm.enabled:
            continue

        # (2) LLM-written tests
        fname = f"test_cip_{slug}.py"
        path = gen_dir / fname
        entry = {"module": m["module"], "file": (GEN_DIR / fname).as_posix(), "mode": "llm", "attempts": 0}
        try:
            ctx = build_module_context(workspace, m["info"], app_summary)
            ctx += "\n\n## SCENARIOS TO COVER\n" + json.dumps(m["scenarios"], indent=1)
            path.write_text(extract_code(llm.complete(load_prompt("test_generation"), ctx, max_tokens=8000)),
                            encoding="utf-8")
        except Exception as e:
            log.warning("LLM test generation failed for %s (%s) – smoke test only", m["module"], str(e)[:200])
            entry.update(status="generation failed", llm_error=str(e)[:300])
            report["files"].append(entry)
            continue

        result = _run(tenv, fname, out_dir, env)
        while (result["failed"] or result["errors"] or result.get("error")) and entry["attempts"] < max_repairs \
                and llm.enabled:
            entry["attempts"] += 1
            log.info("  repairing %s (attempt %d): %d failing", fname, entry["attempts"], result["failed"] + result["errors"])
            ctx = (build_module_context(workspace, m["info"], app_summary) +
                   f"\n\n## CURRENT TEST FILE\n```python\n{path.read_text(encoding='utf-8')}\n```\n\n"
                   f"## PYTEST FAILURES\n{json.dumps(result['failures'][:15], indent=1) or result.get('error', '')}"
                   f"\n\n## OUTPUT TAIL\n{result['output_tail'][-3000:]}")
            try:
                path.write_text(extract_code(llm.complete(load_prompt("test_repair"), ctx, max_tokens=8000)), encoding="utf-8")
            except Exception as e:
                log.warning("repair failed: %s", e)
                break
            result = _run(tenv, fname, out_dir, env)

        # still failing after repair -> prune failing tests; if nothing usable is left -> quarantine the file
        if result["failed"] or result["errors"] or result.get("error"):
            removed = prune_failing(path, result["failures"]) if result["failures"] and result["total"] else -1
            if removed > 0:
                report["removed_tests"] += [dict(f, module=m["module"]) for f in result["failures"]]
                result = _run(tenv, fname, out_dir, env)
            if result["failed"] or result["errors"] or result.get("error") or result["total"] == 0:
                quarantine.mkdir(parents=True, exist_ok=True)
                shutil.move(str(path), quarantine / fname)
                report["quarantined"].append({"module": m["module"], "file": fname,
                                              "reason": (result.get("error") or json.dumps(result["failures"][:3]))[:1500]})
                entry["status"] = "quarantined"
                report["files"].append(entry)
                continue

        src = path.read_text(encoding="utf-8")
        stubs = stubbed_imports(src, m["info"]["imports"])
        if stubs:
            log.warning("%s replaces real modules with fakes (%s) – its passes do not prove those imports work; "
                        "the smoke test shows the real behaviour", fname, ", ".join(stubs))
            report["stubbed_imports"].append({"module": m["module"], "file": fname, "modules": stubs})
            entry["stubbed_imports"] = stubs
        for reason in re.findall(r'CIP suspected defect:\s*([^"\']+)', src):
            report["suspected_defects"].append({"module": m["module"], "defect": reason.strip()})
        entry.update(status="ok", passed=result["passed"], xfailed=result["xfailed"])
        report["files"].append(entry)

    report["generated_ok"] = sum(1 for f in report["files"] if f["status"] == "ok")
    return report
